//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 05:01:12 PM CEST 
//


package rs.gov.parlament.amandman;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Predlagac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Usvojen_od" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pravni_osnov_za_donosenje_amandmana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cilja_donosenja_amandmana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Mesto" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Vreme" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "predlagac",
    "usvojenOd",
    "pravniOsnovZaDonosenjeAmandmana",
    "ciljaDonosenjaAmandmana"
})
@XmlRootElement(name = "Glavni_deo")
public class GlavniDeo {

    @XmlElement(name = "Predlagac", required = true)
    protected String predlagac;
    @XmlElement(name = "Usvojen_od", required = true)
    protected String usvojenOd;
    @XmlElement(name = "Pravni_osnov_za_donosenje_amandmana", required = true)
    protected String pravniOsnovZaDonosenjeAmandmana;
    @XmlElement(name = "Cilja_donosenja_amandmana", required = true)
    protected String ciljaDonosenjaAmandmana;
    @XmlAttribute(name = "Mesto")
    @XmlSchemaType(name = "anySimpleType")
    protected String mesto;
    @XmlAttribute(name = "Vreme")
    @XmlSchemaType(name = "anySimpleType")
    protected String vreme;
    @XmlAttribute(name = "Datum")
    @XmlSchemaType(name = "anySimpleType")
    protected String datum;

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredlagac(String value) {
        this.predlagac = value;
    }

    /**
     * Gets the value of the usvojenOd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsvojenOd() {
        return usvojenOd;
    }

    /**
     * Sets the value of the usvojenOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsvojenOd(String value) {
        this.usvojenOd = value;
    }

    /**
     * Gets the value of the pravniOsnovZaDonosenjeAmandmana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravniOsnovZaDonosenjeAmandmana() {
        return pravniOsnovZaDonosenjeAmandmana;
    }

    /**
     * Sets the value of the pravniOsnovZaDonosenjeAmandmana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravniOsnovZaDonosenjeAmandmana(String value) {
        this.pravniOsnovZaDonosenjeAmandmana = value;
    }

    /**
     * Gets the value of the ciljaDonosenjaAmandmana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiljaDonosenjaAmandmana() {
        return ciljaDonosenjaAmandmana;
    }

    /**
     * Sets the value of the ciljaDonosenjaAmandmana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiljaDonosenjaAmandmana(String value) {
        this.ciljaDonosenjaAmandmana = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the vreme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVreme() {
        return vreme;
    }

    /**
     * Sets the value of the vreme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVreme(String value) {
        this.vreme = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

}
