//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 01:08:35 PM CEST 
//


package rs.gov.parlament.odluka;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.gov.parlament.odluka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.gov.parlament.odluka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GlavniDeo }
     * 
     */
    public GlavniDeo createGlavniDeo() {
        return new GlavniDeo();
    }

    /**
     * Create an instance of {@link UnutrasnjaPodela }
     * 
     */
    public UnutrasnjaPodela createUnutrasnjaPodela() {
        return new UnutrasnjaPodela();
    }

    /**
     * Create an instance of {@link TPododeljak }
     * 
     */
    public TPododeljak createTPododeljak() {
        return new TPododeljak();
    }

    /**
     * Create an instance of {@link TClan }
     * 
     */
    public TClan createTClan() {
        return new TClan();
    }

    /**
     * Create an instance of {@link TStav }
     * 
     */
    public TStav createTStav() {
        return new TStav();
    }

    /**
     * Create an instance of {@link TTacka }
     * 
     */
    public TTacka createTTacka() {
        return new TTacka();
    }

    /**
     * Create an instance of {@link TPodtacka }
     * 
     */
    public TPodtacka createTPodtacka() {
        return new TPodtacka();
    }

    /**
     * Create an instance of {@link TDeo }
     * 
     */
    public TDeo createTDeo() {
        return new TDeo();
    }

    /**
     * Create an instance of {@link TGlava }
     * 
     */
    public TGlava createTGlava() {
        return new TGlava();
    }

    /**
     * Create an instance of {@link TOdeljak }
     * 
     */
    public TOdeljak createTOdeljak() {
        return new TOdeljak();
    }

    /**
     * Create an instance of {@link GlavniDeo.UsvojeniAkt }
     * 
     */
    public GlavniDeo.UsvojeniAkt createGlavniDeoUsvojeniAkt() {
        return new GlavniDeo.UsvojeniAkt();
    }

    /**
     * Create an instance of {@link GlavniDeo.AktUProceduri }
     * 
     */
    public GlavniDeo.AktUProceduri createGlavniDeoAktUProceduri() {
        return new GlavniDeo.AktUProceduri();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link UnutrasnjaPodela.Deo }
     * 
     */
    public UnutrasnjaPodela.Deo createUnutrasnjaPodelaDeo() {
        return new UnutrasnjaPodela.Deo();
    }

    /**
     * Create an instance of {@link TPododeljak.Clan }
     * 
     */
    public TPododeljak.Clan createTPododeljakClan() {
        return new TPododeljak.Clan();
    }

    /**
     * Create an instance of {@link TClan.Stav }
     * 
     */
    public TClan.Stav createTClanStav() {
        return new TClan.Stav();
    }

    /**
     * Create an instance of {@link TStav.Tacka }
     * 
     */
    public TStav.Tacka createTStavTacka() {
        return new TStav.Tacka();
    }

    /**
     * Create an instance of {@link TTacka.Podtacka }
     * 
     */
    public TTacka.Podtacka createTTackaPodtacka() {
        return new TTacka.Podtacka();
    }

    /**
     * Create an instance of {@link TPodtacka.Alineja }
     * 
     */
    public TPodtacka.Alineja createTPodtackaAlineja() {
        return new TPodtacka.Alineja();
    }

    /**
     * Create an instance of {@link TDeo.Glava }
     * 
     */
    public TDeo.Glava createTDeoGlava() {
        return new TDeo.Glava();
    }

    /**
     * Create an instance of {@link TGlava.Odeljak }
     * 
     */
    public TGlava.Odeljak createTGlavaOdeljak() {
        return new TGlava.Odeljak();
    }

    /**
     * Create an instance of {@link TOdeljak.Pododeljak }
     * 
     */
    public TOdeljak.Pododeljak createTOdeljakPododeljak() {
        return new TOdeljak.Pododeljak();
    }

}
