//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 01:09:02 PM CEST 
//


package rs.gov.parlament.amandman;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.parlament.gov.rs/amandman}Unutrasnja_podela"/>
 *         &lt;element ref="{http://www.parlament.gov.rs/amandman}Glavni_deo"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Naziv" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unutrasnjaPodela",
    "glavniDeo"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    @XmlElement(name = "Unutrasnja_podela", required = true)
    protected UnutrasnjaPodela unutrasnjaPodela;
    @XmlElement(name = "Glavni_deo", required = true)
    protected GlavniDeo glavniDeo;
    @XmlAttribute(name = "Naziv")
    @XmlSchemaType(name = "anySimpleType")
    protected String naziv;

    /**
     * Gets the value of the unutrasnjaPodela property.
     * 
     * @return
     *     possible object is
     *     {@link UnutrasnjaPodela }
     *     
     */
    public UnutrasnjaPodela getUnutrasnjaPodela() {
        return unutrasnjaPodela;
    }

    /**
     * Sets the value of the unutrasnjaPodela property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnutrasnjaPodela }
     *     
     */
    public void setUnutrasnjaPodela(UnutrasnjaPodela value) {
        this.unutrasnjaPodela = value;
    }

    /**
     * Gets the value of the glavniDeo property.
     * 
     * @return
     *     possible object is
     *     {@link GlavniDeo }
     *     
     */
    public GlavniDeo getGlavniDeo() {
        return glavniDeo;
    }

    /**
     * Sets the value of the glavniDeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlavniDeo }
     *     
     */
    public void setGlavniDeo(GlavniDeo value) {
        this.glavniDeo = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

}
